[package]
name = "wikidot-https-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
ciborium = "0.2.2"
clap = { version = "4.6.7", features = ["derive"] }
console = "0.16.6"
ftml = { git = "https://github.com/thief-sty/ftml", rev = "9cdb1de4a8d3e0912ba56d5acd6b990360fc9ff2" }
indicatif = { version = "0.18.6", features = ["rayon"] }
rayon = "1.12.0"
regex = "1.13.1"
rusqlite = { version = "0.40.2", features = ["bundled"] }
