use indicatif::ParallelProgressIterator;
use indicatif::ProgressBar;
use rayon::iter::IntoParallelRefMutIterator;
use rayon::iter::ParallelIterator;
use rusqlite::OpenFlags;
use rusqlite::params;
use std::collections::HashMap;
use std::collections::HashSet;
use std::hash::DefaultHasher;
use std::hash::Hasher;
use std::path::PathBuf;
use std::sync::mpsc;
use std::sync::mpsc::Sender;
use std::time::Duration;
use std::time::Instant;

use clap::Parser;
use rusqlite::Connection;

#[derive(Parser)]
struct Cli {
    /// The path to the SQLite database generated by `wikidot-css-extractor`.
    db: PathBuf,
    /// The Wikidot site handle (e.g. `scp-wiki`)
    site: String,
    /// The path to the SQLite database that contains the cached FTML syntax trees.
    #[arg(long, default_value = "wikidot-https-helper-cache.sqlite")]
    cache_db: PathBuf,
}

struct Page {
    url: String,
    slug: String,
    source: String,
}

fn main() {
    let args = Cli::parse();

    let db = Connection::open_with_flags(args.db, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .expect("Failed to open a connection to the database");

    let mut pages = {
        let mut stmt = db
            .prepare("SELECT * FROM pages WHERE url LIKE ?")
            .expect("Failed to prepare SQL `SELECT` statement over the source database");
        let pattern = format!("http://{}.wikidot.com/%", args.site);
        stmt.query_map([pattern], |row| {
            Ok(Page {
                url: row.get("url")?,
                slug: row.get("slug")?,
                source: row.get("source")?,
            })
        })
        .expect("Failed to query the database")
        .map(|maybe_page| maybe_page.expect("Failed to iterate through a page"))
        .collect::<Vec<_>>()
    };

    let npages = pages.len() as u64;

    let cache_db =
        Connection::open(args.cache_db).expect("Failed to open a connection to the cache database");
    let cache = match cache_db.prepare("SELECT url, hash, hosts FROM cache") {
        Ok(mut stmt) => {
            let mut map = HashMap::new();
            stmt.query_map([], |row| {
                Ok((
                    row.get::<_, String>("url")?,
                    (row.get::<_, i64>("hash")?, row.get::<_, Vec<u8>>("hosts")?),
                ))
            })
            .expect("Failed to query the cache database")
            .map(|maybe_index| maybe_index.expect("Failed to iterate through a cache row"))
            .for_each(|(url, data)| {
                map.insert(url, data);
            });
            map
        }
        Err(rusqlite::Error::SqliteFailure(_, Some(msg))) if msg == "no such table: cache" => {
            HashMap::new()
        }
        Err(error) => panic!("Failed to query the cache database: {}", error),
    };
    let cache_queue = spawn_cache_thread(cache_db);

    let progress_bar = ProgressBar::new(npages);
    let parallel_bar = progress_bar.clone();

    let hosts: HashSet<String> = pages
        .par_iter_mut()
        .progress_with(progress_bar)
        .map(|page| {
            let mut hasher = DefaultHasher::new();
            hasher.write(page.source.as_bytes());
            let hash = hasher.finish() as i64;

            if let Some((cached_hash, serialized_hosts)) = cache.get(&page.url)
                && *cached_hash == hash
            {
                parallel_bar.println(format!(
                    "{} {}",
                    &page.slug,
                    console::style("- cache hit").dim()
                ));
                let hosts: HashSet<String> = ciborium::from_reader(serialized_hosts.as_slice())
                    .expect("Failed to deserialize a host list");
                return hosts;
            }

            parallel_bar.println(format!(
                "{} {}",
                &page.slug,
                console::style("- searching").dim()
            ));

            let hosts: HashSet<String> = todo!("find http:// hosts in the source");

            let mut serialized_hosts = Vec::new();
            ciborium::into_writer(&hosts, &mut serialized_hosts)
                .expect("Failed to serialize a warning list");

            cache_queue
                .send(Cacheable {
                    url: page.url.clone(),
                    hash,
                    hosts: serialized_hosts,
                })
                .expect("The caching thread is gone");
            hosts
        })
        .reduce(HashSet::new, |mut a, mut b| {
            // always merge the smaller set into the larger one, in order to rehash fewer elements
            if a.len() < b.len() {
                std::mem::swap(&mut a, &mut b);
            }
            a.extend(b);
            a
        });

    println!("{} hosts generated", hosts.len());
}

struct Cacheable {
    url: String,
    hash: i64, // u64 does not implement rusqlite::types::ToSql
    hosts: Vec<u8>,
}

fn spawn_cache_thread(mut db: Connection) -> Sender<Cacheable> {
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        db.execute("CREATE TABLE IF NOT EXISTS cache (url TEXT PRIMARY KEY, hash BLOB NOT NULL, hosts BLOB NOT NULL)", []).expect("Failed to ensure that the cache table exists");

        let interval = Duration::from_secs(1);
        let mut next_run = Instant::now();

        loop {
            let start_time = Instant::now();
            std::thread::sleep(next_run.saturating_duration_since(start_time));

            if let Ok(transaction) = db.transaction() {
                for Cacheable { url, hash, hosts } in rx.try_iter() {
                    transaction.execute("INSERT INTO cache(url, hash, hosts) VALUES(?, ?, ?, ?) ON CONFLICT(url) DO UPDATE SET hash=?, hosts=?", params![url, hash, hosts,  hash, hosts]).expect("Failed to cache a row");
                }
                transaction
                    .commit()
                    .expect("Failed to commit a cache transaction");
            }

            next_run = start_time + interval;
        }
    });
    tx
}
